const AnimeData=[
    {
        name:"Naruto",
        type:"anime series",
        status:"completed",
        episode:"220",
        genre:"Action, Adventure, Comedy, Super Power, Martial Arts, Shounen",
        source:"manga",
        duration:"23 min. per ep."
    },
    {
        name:"Naruto Shippuden",
        type:"anime Series",
        status:"completed",
        episode:"500",
        genre:"Action, Adventure, Comedy, Super Power, Martial Arts, Shounen",
        source:"manga",
        duration:"23 min. per ep."
    },
    {
        name:"Boruto: Naruto Next Generations",
        type:"anime Series",
        status:"ongoing",
        genre:"Action, Adventure, Comedy, Super Power, Martial Arts, Shounen",
        source:"manga",
        duration:"23 min. per ep."
    },
    {
        name: "Death Note",
        Type: "anime series",
        Episodes: 37, 
        Status: "Finished Airing",
        Aired: "Oct 4, 2006 to Jun 27, 2007",
        Premiered: "Fall 2006",
        Broadcast: "Wednesdays at 00: 56(JST",
        Producers: "VAP, Konami, Ashi Production, Nippon",
        Television:"Network, Shueisha",
        Licensors: "Viz Media",
        Studios: "Madhouse",
        Source: "Manga",
        Genres: "Mystery, Police, Psychological, Supernatural, Thriller, Shounen",
        Duration: "23 min.per ep.",
        Rating: "R – 17+ (violence & profanity)",
    },
    {
        name: "Boruto: Naruto Next Generations",
        type: "anime Series",
        status: "ongoing",
        genre: "Action, Adventure, Comedy, Super Power, Martial Arts, Shounen",
        source: "manga",
        duration: "23 min. per ep."
    },
    {
        name: "Another",
        Type: "anime series",
        Episodes: 12,
        Status: "Finished Airing",
        Aired: "Jan 10, 2012 to Mar 27, 2012",
        Premiered: "Winter 2012",
        Broadcast: "UnKnown",
        Producers: "Lantis, Kadokawa Shoten, Toho, KlockWorx, Bandai Namco Live Creative, NTT Docomo Licensors: Sentai Filmworks",
        Studios: "P.A. Works",
        Source: "Light Novel",
        Genres: "Mystery, Horror, Supernatural, Thriller, School",
        Duration: "24 min.per ep.",
        Rating: "R – 17+ (violence & profanity)",
    },
    {
        name: "Dragon Ball",
        Type: "anime series",
        Episodes:"(Kai + Super + GT + Movies + OVAs)",
        Status: "Finished Airing",
        Aired: "Jul 5, 2015 to Mar 25, 2018",
        Premiered: "Summer 2015",
        Broadcast: "Sundays at 09:00 (JST)",
        Producers: "Yomiko Advertising, Fuji TV",
        Licensors:"Funimation",
        Studios: "Toei Animation",
        Source: "Manga",
        Genres: "Action, Adventure, Comedy, Super Power, Martial Arts, Fantasy, Shounen",
        Duration: "23 min.per ep.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "Your Lie in April",
        Discription: "Music accompanies the path of the human metronome, the prodigious pianist Kousei Arima. But after the passing of his mother, Saki Arima, Kousei falls into a downward spiral, rendering him unable to hear the sound of his own piano. Two years later, Kousei still avoids the piano, leaving behind his admirers and rivals, and lives a colorless life alongside his friends Tsubaki Sawabe and Ryouta Watari. However, everything changes when he meets a beautiful violinist, Kaori Miyazono, who stirs up his world and sets him on a journey to face music again. Based on the manga series of the same name, Shigatsu wa Kimi no Uso approaches the story of Kousei’s recovery as he discovers that music is more than playing each note perfectly, and a single melody can bring in the fresh spring air of April.",
        Type: "anime series",
        Episodes: "22",
        Status: "Finished Airing",
        Aired: "Oct 10, 2014 to Mar 20, 2015",
        Premiered: "Fall 2014",
        Producers: "Yomiko Advertising, Fuji TV",
        Licensors: "Aniplex of America",
        Studios: "A-1 Pictures",
        Source: "Manga",
        Genres: "Drama, Music, Romance, School, Shounen",
        Duration: "22 min.per ep.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "My Hero Achedemia",
        Description: "The appearance of “quirks,” newly discovered super powers, has been steadily increasing over the years, with 80 percent of humanity possessing various abilities from manipulation of elements to shapeshifting. This leaves the remainder of the world completely powerless, and Izuku Midoriya is one such individual. Since he was a child, the ambitious middle schooler has wanted nothing more than to be a hero.Izuku’s unfair fate leaves him admiring heroes and taking notes on them whenever he can.But it seems that his persistence has borne some fruit: Izuku meets the number one hero and his personal idol, All Might.All Might’s quirk is a unique ability that can be inherited, and he has chosen Izuku to be his successor! Enduring many months of grueling training, Izuku enrolls in UA High, a prestigious high school famous for its excellent hero training program, and this year’s freshmen look especially promising.With his bizarre but talented classmates and the looming threat of a villainous organization, Izuku will soon learn what it really means to be a hero.",
        Type: "anime series",
        Episodes: " (Seasons 1-5 + Movies + OVAs)",
        Status: "Finished Airing",
        Aired: "Apr 3, 2016 to Jun 26, 2016",
        Premiered: "Spring 2016",
        Licensors: "Funimation",
        Studios: "Bones",
        Source: "Manga",
        Genres: "Action, Comedy, School, Shounen, Super Power",
        Duration: "24 min.per ep.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "Kokoro Connect",
        Description: "When five students at Yamaboshi Academy realize that there are no clubs where they fit in, they band together to form the Student Cultural Society, or “StuCS” for short. The club consists of: Taichi Yaegashi, a hardcore wrestling fan; Iori Nagase, an indecisive optimist; Himeko Inaba, a calm computer genius; Yui Kiriyama, a petite karate practitioner; and Yoshifumi Aoki, the class clown. One day, Aoki and Yui experience a strange incident when, without warning, they switch bodies for a short period of time. As this supernatural phenomenon continues to occur randomly amongst the five friends, they begin to realize that it is not just fun and games. Now forced to become closer than ever, they soon discover each other’s hidden secrets and emotional scars, which could end up tearing the StuCS and their friendship apart. ",
        Type: "anime series",
        Episodes: "13",
        Status: "Finished Airing",
        Aired: " Jul 8, 2012 to Sep 30, 2012",
        Premiered: "Summer 2012",
        Licensors: "Sentai Filmworks",
        Studios: "Silver Link",
        Source: "Light Novel",
        Genres: "Slice of Life, Comedy, Supernatural, Drama, Romance, School",
        Duration: "24 min.per ep.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "Attack on Titan",
        Description: "Centuries ago, mankind was slaughtered to near extinction by monstrous humanoid creatures called titans, forcing humans to hide in fear behind enormous concentric walls. What makes these giants truly terrifying is that their taste for human flesh is not born out of hunger but what appears to be out of pleasure. To ensure their survival, the remnants of humanity began living within defensive barriers, resulting in one hundred years without a single titan encounter. However, that fragile calm is soon shattered when a colossal titan manages to breach the supposedly impregnable outer wall, reigniting the fight for survival against the man-eating abominations.\nAfter witnessing a horrific personal loss at the hands of the invading creatures, Eren Yeager dedicates his life to their eradication by enlisting into the Survey Corps, an elite military unit that combats the merciless humanoids outside the protection of the walls.Based on Hajime Isayama’s award- winning manga, Shingeki no Kyojin follows Eren, along with his adopted sister Mikasa Ackerman and his childhood friend Armin Arlert, as they join the brutal war against the titans and race to discover a way of defeating them before the last walls are breached.",
        Type: "anime series",
        Episodes: "1-3 + Attack on Titan ~Chronicle~ (Shingeki no Kyojin – Chronicle)",
        Status: "Finished Airing",
        Aired: "Apr 7, 2013 to Sep 29, 2013",
        Premiered: "Spring 2013",
        Broadcast: "Sundays at 01:58 (JST)",
        Licensors: "Funimation",
        Studios: "Wit Studio",
        Source: "Manga",
        Genres: "Action, Military, Mystery, Super Power, Drama, Fantasy, Shounen",
        Duration: "24 min.per ep.",
        Rating: " R – 17+ (violence & profanity",
    },
    {
        name: "Black Clover",
        Description: "Asta and Yuno were abandoned at the same church on the same day. Raised together as children, they came to know of the “Wizard King”—a title given to the strongest mage in the kingdom—and promised that they would compete against each other for the position of the next Wizard King. However, as they grew up, the stark difference between them became evident. While Yuno is able to wield magic with amazing power and control, Asta cannot use magic at all and desperately tries to awaken his powers by training physically.\nWhen they reach the age of 15, Yuno is bestowed a spectacular Grimoire with a four- leaf clover, while Asta receives nothing.However, soon after, Yuno is attacked by a person named Lebuty, whose main purpose is to obtain Yuno’s Grimoire.Asta tries to fight Lebuty, but he is outmatched.Though without hope and on the brink of defeat, he finds the strength to continue when he hears Yuno’s voice.Unleashing his inner emotions in a rage, Asta receives a five - leaf clover Grimoire, a “Black Clover” giving him enough power to defeat Lebuty.A few days later, the two friends head out into the world, both seeking the same goal—to become the Wizard King!",
        Type: "anime series",
        Episodes: "157",
        Status: "Finished Airing",
        Aired: "Oct 3, 2017 to ?",
        Premiered: "Fall 2017",
        Licensors: "Funimation,Crunchyroll",
        Studios: "Studio Pierrot",
        Source: "Manga",
        Genres: "Action, Comedy, Magic, Fantasy, Shounen",
        Duration: "23 min.per ep.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "Sword art Online",
        Description: "In the year 2022, virtual reality has progressed by leaps and bounds, and a massive online role-playing game called Sword Art Online (SAO) is launched. With the aid of “NerveGear” technology, players can control their avatars within the game using nothing but their own thoughts. Kazuto Kirigaya, nicknamed “Kirito,” is among the lucky few enthusiasts who get their hands on the first shipment of the game. He logs in to find himself, with ten-thousand others, in the scenic and elaborate world of Aincrad, one full of fantastic medieval weapons and gruesome monsters.\nHowever, in a cruel turn of events, the players soon realize they cannot log out; the game’s creator has trapped them in his new world until they complete all one hundred levels of the game.In order to escape Aincrad, Kirito will now have to interact and cooperate with his fellow players.Some are allies, while others are foes, like Asuna Yuuki, who commands the leading group attempting to escape from the ruthless game.To make matters worse, Sword Art Online is not all fun and games: if they die in Aincrad, they die in real life.Kirito must adapt to his new reality, fight for his survival, and hopefully break free from his virtual hell.",
        Type: "anime series",
        Episodes: "(Seasons 1-3 + Sword Art Online Alternative Gun Gale Online + Movie)",
        Status: "Finished Airing",
        Licensors: "Aniplex of America",
        Studios: "A-1 Pictures",
        Source: "Light Novel",
        Genres: "Action, Adventure, Fantasy, Game, Romance",
        Duration: "23 min.per ep.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "Demon Slayer",
        Description: "Ever since the death of his father, the burden of supporting the family has fallen upon Tanjirou Kamado’s shoulders. Though living impoverished on a remote mountain, the Kamado family are able to enjoy a relatively peaceful and happy life. One day, Tanjirou decides to go down to the local village to make a little money selling charcoal.\nOn his way back, night falls, forcing Tanjirou to take shelter in the house of a strange man, who warns him of the existence of flesh- eating demons that lurk in the woods at night.When he finally arrives back home the next day, he is met with a horrifying sight—his whole family has been slaughtered.Worse still, the sole survivor is his sister Nezuko, who has been turned into a bloodthirsty demon.Consumed by rage and hatred, Tanjirou swears to avenge his family and stay by his only remaining sibling.Alongside the mysterious group calling themselves the Demon Slayer Corps, Tanjirou will do whatever it takes to slay the demons and protect the remnants of his beloved sister’s humanity.",
        Type: "anime series",
        Episodes: 26,
        Status: "Finished Airing",
        Aired: "Apr 6, 2019 to Sep 28, 2019",
        Premiered: "Spring 2019",
        Licensors: "Aniplex of America",
        Studios: "ufotable",
        Source: "Manga",
        Genres: "Action, Demons, Historical, Shounen, Supernatural",
        Duration: "23 min.per ep.",
        Rating: "R – 17+ (violence & profanity)",
    },
    {
        name: "DR. Stone",
        Description: "After five years of harboring unspoken feelings, high-schooler Taiju Ooki is finally ready to confess his love to Yuzuriha Ogawa. Just when Taiju begins his confession however, a blinding green light strikes the Earth and petrifies mankind around the world—turning every single human into stone. Several millennia later, Taiju awakens to find the modern world completely nonexistent, as nature has flourished in the years humanity stood still.\nAmong a stone world of statues, Taiju encounters one other living human: his science- loving friend Senkuu, who has been active for a few months.Taiju learns that Senkuu has developed a grand scheme—to launch the complete revival of civilization with science.Taiju’s brawn and Senkuu’s brains combine to forge a formidable partnership, and they soon uncover a method to revive those petrified.However, Senkuu’s master plan is threatened when his ideologies are challenged by those who awaken.All the while, the reason for mankind’s petrification remains unknown.",
        Type: "anime series",
        Episodes: "24",
        Status: "Finished Airing",
        Aired: "Jul 5, 2019 to Dec 13, 2019",
        Premiered: "Summer 2019",
        Licensors: "Funimation, Crunchyroll",
        Studios: "TMS Entertainment",
        Source: "Manga",
        Genres: " Sci-Fi, Adventure, Comedy, Shounen",
        Duration: "24 min.per ep.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "Tokyo Ghoul",
        Description: "Tokyo has become a cruel and merciless city—a place where vicious creatures called “ghouls” exist alongside humans. The citizens of this once great metropolis live in constant fear of these bloodthirsty savages and their thirst for human flesh. However, the greatest threat these ghouls pose is their dangerous ability to masquerade as humans and blend in with society. Based on the best-selling supernatural horror manga by Sui Ishida, Tokyo Ghoul follows Ken Kaneki, a shy, bookish college student, who is instantly drawn to Rize Kamishiro, an avid reader like himself. However, Rize is not exactly who she seems, and this unfortunate meeting pushes Kaneki into the dark depths of the ghouls’ inhuman world. In a twist of fate, Kaneki is saved by the enigmatic waitress Touka Kirishima, and thus begins his new, secret life as a half-ghoul/half-human who must find a way to integrate into both societies.",
        Type: "anime series",
        Episodes: "(Seasons 1-3 + OVAs)",
        Status: "Finished Airing",
        Aired: "Jul 4, 2014 to Sep 19, 2014",
        Premiered: "Summer 2014",
        Licensors: "Funimation",
        Studios: "Studio Pierrot",
        Source: "Manga",
        Genres: "Action, Mystery, Horror, Psychological, Supernatural, Drama, Seinen",
        Duration: "24 min.per ep.",
        Rating: "R – 17+ (violence & profanity)",
    },
    {
        name: "Steins Gate",
        Description: "The self-proclaimed mad scientist Rintarou Okabe rents out a room in a rickety old building in Akihabara, where he indulges himself in his hobby of inventing prospective “future gadgets” with fellow lab members: Mayuri Shiina, his air-headed childhood friend, and Hashida Itaru, a perverted hacker nicknamed “Daru.” The three pass the time by tinkering with their most promising contraption yet, a machine dubbed the “Phone Microwave,” which performs the strange function of morphing bananas into piles of green gel.\nThough miraculous in itself, the phenomenon doesn’t provide anything concrete in Okabe’s search for a scientific breakthrough; that is, until the lab members are spurred into action by a string of mysterious happenings before stumbling upon an unexpected success—the Phone Microwave can send emails to the past, altering the flow of history.Adapted from the critically acclaimed visual novel by 5pb.and Nitroplus, Steins; Gate takes Okabe through the depths of scientific theory and practicality.Forced across the diverging threads of past and present, Okabe must shoulder the burdens that come with holding the key to the realm of time.",
        Type: "anime series",
        Episodes: "(Seasons 1-2 + Movie + OVAs)",
        Status: "Finished Airing",
        Aired: "Apr 6, 2011 to Sep 14, 2011",
        Premiered: "Spring 2011",
        Licensors: "Funimation",
        Studios: "White Fox",
        Source: "Visual Novel",
        Genres: "Thriller, Si-Fi",
        Duration: "24 min.per ep.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "Orange",
        Description: "Naho Takamiya’s first day of her sophomore year of high school is off to an uneasy start. After waking up late, she receives a strange letter addressed to her. However, the letter is from herself—10 years in the future! At first, Naho is skeptical of the note; yet, after witnessing several events described to take place, she realizes the letter really is from her 26-year-old self.\nThe note details that Naho’s future life is filled with regrets, and she hopes that her younger self can correct the mistakes that were made in the past.The letter also warns her to keep a close eye on the new transfer student, Kakeru Naruse.Naho must be especially careful in making decisions involving him, as Kakeru is not around in the future.With the letter as her guide, Naho now has the power to protect Kakeru before she comes to regret it once more.",
        Type: "anime series",
        Episodes: "13",
        Status: "Finished Airing",
        Aired: "Jul 4, 2016 to Sep 26, 2016",
        Premiered: "Summer 2016",
        Licensors: "Funimation, Crunchyroll",
        Studios: "Telecom Animation Flim",
        Source: "Manga",
        Genres: "Sci-Fi, Drama, Romance, School, Shoujo",
        Duration: "24 min.per ep.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "ReLIFE",
        Description: "Dismissed as a hopeless loser by those around him, 27-year-old Arata Kaizaki bounces around from one job to another after quitting his first company. His unremarkable existence takes a sharp turn when he meets Ryou Yoake, a member of the ReLife Research Institute, who offers Arata the opportunity to change his life for the better with the help of a mysterious pill.\nTaking it without a second thought, Arata awakens the next day to find that his appearance has reverted to that of a 17-year - old.Arata soon learns that he is now the subject of a unique experiment and must attend high school as a transfer student for one year.Though he initially believes it will be a cinch due to his superior life experience, Arata is proven horribly wrong on his first day: he flunks all his tests, is completely out of shape, and can’t keep up with the new school policies that have cropped up in the last 10 years.Furthermore, Ryou has been assigned to observe him, bringing Arata endless annoyance.ReLIFE follows Arata’s struggle to adjust to his hectic new lifestyle and avoid repeating his past mistakes, all while slowly discovering more about his fellow classmates.",
        Type: "anime series",
        Episodes:"13",
        Status: "Finished Airing",
        Aired: "Jul 2, 2016 to Sep 24, 2016",
        Premiered: "Summer 2016",
        Licensors:"Funimation, Crucnhyroll",
        Studios: "TMS Entertainment",
        Source: "Web Manga",
        Genres: "Slice of Life, Romance, School",
        Duration: "23 min.per ep.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "Re:ZERO",
        Description: "When Subaru Natsuki leaves the convenience store, the last thing he expects is to be wrenched from his everyday life and dropped into a fantasy world. Things aren’t looking good for the bewildered teenager; however, not long after his arrival, he is attacked by some thugs. Armed with only a bag of groceries and a now useless cell phone, he is quickly beaten to a pulp. Fortunately, a mysterious beauty named Satella, in hot pursuit after the one who stole her insignia, happens upon Subaru and saves him. In order to thank the honest and kindhearted girl, Subaru offers to help in her search, and later that night, he even finds the whereabouts of that which she seeks. But unbeknownst to them, a much darker force stalks the pair from the shadows, and just minutes after locating the insignia, Subaru and Satella are brutally murdered. However, Subaru immediately reawakens to a familiar scene—confronted by the same group of thugs, meeting Satella all over again—the enigma deepens as history inexplicably repeats itself.",
        Type: "anime series",
        Episodes:"(Seasons 1-2 + Movie + OVAs)",
        Status: "Finished Airing",
        Aired: "Apr 4, 2016 to Sep 19, 2016",
        Premiered: "Spring 2016",
        Licensors:"Funimation",
        Studios: "White Fox",
        Source: "Light Novel",
        Genres: "Psychological, Drama, Thriller, Fantasy",
        Duration: "25 min.per ep.",
        Rating: "R – 17+ (violence & profanity)",
    },
    {
        name: "Dororo",
        Description: "The greedy samurai lord Daigo Kagemitsu’s land is dying, and he would do anything for power, even renounce Buddha and make a pact with demons. His prayers are answered by 12 demons who grant him the power he desires by aiding his prefecture’s growth, but at a price. When Kagemitsu’s first son is born, the boy has no limbs, no nose, no eyes, no ears, nor even skin—yet still, he lives. This child is disposed of in a river and forgotten.\nBut as luck would have it, he is saved by a medicine man who provides him with prosthetics and weapons, allowing for him to survive and fend for himself.The boy lives and grows, and although he cannot see, hear, or feel anything, he must defeat the demons that took him as sacrifice.With the death of each one, he regains a part of himself that is rightfully his.For many years he wanders alone, until one day an orphan boy, Dororo, befriends him.The unlikely pair of castaways now fight for their survival and humanity in an unforgiving, demon- infested world.",
        Type: "anime series",
        Episodes: "24",
        Status: "Finished Airing",
        Aired: "Jan 7, 2019 to Jun 24, 2019",
        Premiered: "Winter 2019",
        Licensors: "None found, add some",
        Studios: "Tezuka Productions, MAPPA",
        Source: "Manga",
        Genres: "Action, Adventure, Demons, Historical, Samurai, Shounen, Supernatural",
        Duration: "24 min.per ep.",
        Rating: "R – 17+ (violence & profanity)",
    },
    {
        name: "The Promished Neverland",
        Description: "Surrounded by a forest and a gated entrance, the Grace Field House is inhabited by orphans happily living together as one big family, looked after by their “Mama,” Isabella. Although they are required to take tests daily, the children are free to spend their time as they see fit, usually playing outside, as long as they do not venture too far from the orphanage—a rule they are expected to follow no matter what.\nHowever, all good times must come to an end, as every few months, a child is adopted and sent to live with their new family, never to be heard from again.However, the three oldest siblings have their suspicions about what is actually happening at the orphanage, and they are about to discover the cruel fate that awaits the children living at Grace Field, including the twisted nature of their beloved Mama.",
        Type: "anime series",
        Episodes: "12",
        Status: "Finished Airing",
        Aired: "Jan 10, 2019 to Mar 29, 2019",
        Premiered: "Winter 2019",
        Licensors: "Aniplex of America",
        Studios: "CloverWorks",
        Source: "Manga",
        Genres: " Sci-Fi, Mystery, Horror, Psychological, Thriller, Shounen",
        Duration: "22 min.per ep.",
        Rating: " R – 17+ (violence & profanity)",
    },
    {
        name: "One Piece",
        Description: "Gol D. Roger was known as the “Pirate King,” the strongest and most infamous being to have sailed the Grand Line. The capture and execution of Roger by the World Government brought a change throughout the world. His last words before his death revealed the existence of the greatest treasure in the world, One Piece.\nIt was this revelation that brought about the Grand Age of Pirates, men who dreamed of finding One Piece—which promises an unlimited amount of riches and fame—and quite possibly the pinnacle of glory and the title of the Pirate King.Enter Monkey D.Luffy, a 17-year - old boy who defies your standard definition of a pirate.Rather than the popular persona of a wicked, hardened, toothless pirate ransacking villages for fun, Luffy’s reason for being a pirate is one of pure wonder: the thought of an exciting adventure that leads him to intriguing people and ultimately, the promised treasure.\nFollowing in the footsteps of his childhood hero, Luffy and his crew travel across the Grand Line, experiencing crazy adventures, unveiling dark mysteries and battling strong enemies, all in order to reach the most coveted of all fortunes—One Piece.",
        Type: "anime series",
        Episodes: "900+",
        Status: "Currently Airing",
        Aired: "Oct 20, 1999 to ?",
        Premiered: "Fall 1999",
        Licensors: "Funimation, 4Kids Entertainment",
        Studios: "Toei Animation",
        Source: "Manga",
        Genres: "Action, Adventure, Comedy, Super Power, Drama, Fantasy, Shounen",
        Duration: "24 min.per ep.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "No guns life",
        Description: "The technology to create powerful cyborg soldiers has been released for public use by the Berühren Corporation. Those outfitted with robotic parts are known as the Extended. Juuzou Inui, one such Extended, was created as a soldier and has no memories of his former life. But now, after the war, he runs a business that takes care of Extended-related incidents around the city.\nRumors of a renegade Extended that kidnapped a child reach his ears; lo and behold, as Juuzo returns to his office, a giant robotic man with a boy on his back crashes in, asking for help.While Juuzou could just turn the guy in and be done with it, something about this situation is too fishy to ignore.It seems that everyone wants hold of this kid and, whether he likes it or not, Juuzou must find out why this Extended is on the run, how it connects to the Berühren Corporation, and just how far the treachery runs in this city.",
        Type: "anime series",
        Episodes: "12",
        Status: "Finished Airing",
        Aired: "Oct 11, 2019 to Dec 27, 2019",
        Premiered: "fall 2019",
        Licensors: "Funimation",
        Studios: "Madhouse",
        Source: "Manga",
        Genres: "Action, Sci-Fi, Drama, Seinen",
        Duration: "24 min.per ep.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "Your Name",
        Description: "Mitsuha Miyamizu, a high school girl, yearns to live the life of a boy in the bustling city of Tokyo—a dream that stands in stark contrast to her present life in the countryside. Meanwhile in the city, Taki Tachibana lives a busy life as a high school student while juggling his part-time job and hopes for a future in architecture. One day, Mitsuha awakens in a room that is not her own and suddenly finds herself living the dream life in Tokyo—but in Taki’s body! Elsewhere, Taki finds himself living Mitsuha’s life in the humble countryside. In pursuit of an answer to this strange phenomenon, they begin to search for one another. Kimi no Na wa. revolves around Mitsuha and Taki’s actions, which begin to have a dramatic impact on each other’s lives, weaving them into a fabric held together by fate and circumstance.",
        Type: "anime movie",
        Episodes: "1",
        Status: "Finished Airing",
        Aired: "Aug 26, 2016",
        Licensors: "Funimation, NYAV Post",
        Studios: "CoMix Wave Films",
        Source: "Original",
        Genres: "Romance, Supernatural, School, Drama",
        Duration: "1 hr. 46 min.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "Ride Your Wave",
        Description: "Entranced by surfing and the sea, Hinako Mukaimizu is a spirited girl who attends college in a coastal city with no consideration for her future career. Her life takes an unexpected turn when a fireworks mishap sets the apartment building she lives in ablaze, where she is saved by a talented firefighter named Minato Hinageshi.\nUpon meeting, the two quickly become acquainted with one another—Hinako is instantly enamored by Minato’s reliable personality and passion for saving others, while Minato is intrigued by surfing and is eager to learn how.As Hinako begins to teach Minato about surfing, the pair eventually fall in love and begin a gentle and devoted relationship.However, while surfing may seem fun and carefree, it can still be a dangerous and unpredictable activity.This is what Hinako learns when a surfing incident completely changes her life, leaving her forced to contemplate her undecided future.In search of her own calling, Hinako begins her journey of self- discovery, keeping Minato by her side as she gradually attempts to find her purpose and ride her own wave. ",
        Type: "anime movie",
        Episodes: "1",
        Status: "Finished Airing",
        Aired: "Jun 21, 2019",
        Licensors: "GKIDS",
        Studios: " Science SARU",
        Source: "Original",
        Genres: "Drama, Romance, Supernatural",
        Duration: "1 hr. 35 min.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "The Garden of Words ",
        Description: "On a rainy morning in Tokyo, Takao Akizuki, an aspiring shoemaker, decides to skip class to sketch designs in a beautiful garden.\nThis is where he meets Yukari Yukino, a beautiful yet mysterious woman, for the very first time.Offering to make her new shoes, Takao continues to meet with Yukari throughout the rainy season, and without even realizing it, the two are able to alleviate the worries hidden in their hearts just by being with each other.However, their personal struggles have not disappeared completely, and as the end of the rainy season approaches, their relationship will be put to the test.",
        Type: "anime movie",
        Episodes: "1",
        Status: "Finished Airing",
        Aired: "May 31, 2013",
        Licensors: "Sentai Filmworks",
        Studios: "CoMix Wave Films",
        Source: "Manga",
        Genres: "Slice of Life, Psychological, Drama, Romance",
        Duration: "46 min",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "I Want to Eat Your Pancreas",
        Description: "The aloof protagonist: a bookworm who is deeply detached from the world he resides in. He has no interest in others and is firmly convinced that nobody has any interest in him either.\nHis story begins when he stumbles across a handwritten book, titled “Living with Dying.” He soon identifies it as a secret diary belonging to his popular, bubbly classmate Sakura Yamauchi.She then confides in him about the pancreatic disease she is suffering from and that her time left is finite.Only her family knows about her terminal illness; not even her best friends are aware.Despite this revelation, he shows zero sympathy for her plight, but caught in the waves of Sakura’s persistent buoyancy, he eventually concedes to accompanying her for her remaining days.As the pair of polar opposites interact, their connection strengthens, interweaving through their choices made with each passing day.Her apparent nonchalance and unpredictability disrupts the protagonist’s impassive flow of life, gradually opening his heart as he discovers and embraces the true meaning of living.",
        Type: "anime movie",
        Episodes: "1",
        Status: "Finished Airing",
        Aired: "Sep 1 2018",
        Licensors: "Aniplex of America",
        Studios: "Studio VOLN",
        Source: "Novel",
        Genres: "Drama",
        Duration: "1 hr. 48 min.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "Into the Forest of Fireflies",
        Description: "Intrigued by the tale of a mountain god, six-year-old Hotaru Takegawa loses her way in the ancient forest while visiting her uncle. Exhausted and desperate for help, Hotaru is thrilled to find a masked forest spirit named Gin. She learns the hard way that she should not touch the boy, or he would disappear.\nIn spite of this, Gin leads Hotaru out of the forest and warns her never to return when she promises to come again with a gift.Paying no heed to his cautionary words, and despite being separated by both distance and planes of existence, Hotaru and Gin become close friends as she visits him every summer.However, their relationship and resolve are put to the test, when romantic feelings conflict with the one and only rule.Based on Yuki Midorikawa’s manga of the same name, Hotarubi no Mori e is a tale of friendship and compromise of two people who should never have crossed paths, as their lives become hopelessly intertwined.",
        Type: "anime movie",
        Episodes: "1",
        Status: "Finished Airing",
        Aired: "Sep 17, 2011",
        Licensors: "one found, add some",
        Studios: "Brain’s Base",
        Source: "Manga",
        Genres: "Drama, Romance, Shoujo, Supernatural",
        Duration: "45 min.",
        Rating: " G – All Ages",
    },
    {
        name: "The Anthem of Heart",
        Description: "Jun Naruse is a chatterbox whose life is colored by fairy tales and happy endings. However, influenced by her deep belief in those tales, she is too naive and trusting, and her words soon shatter her family’s bond when she inadvertently reveals her father’s affair. Naruse is scarred for life after being blamed for her parent’s divorce, and her regrets soon manifest into a fairy egg—a being who seals her mouth from speaking in order to protect everyone’s happy ending. Now, even in high school, Naruse’s speech remains locked by the fairy egg. Even trying to speak causes her stomach to twist. Though unable to convey her thoughts through words, she is unexpectedly chosen to perform in a musical alongside three other students: Takumi Sakagami, Natsuki Nitou, and Daiki Tasaki. Naruse makes her way to the club room to reject the daunting task, but changes her mind when she overhears Sakagami’s beautiful singing. Perhaps the fairy egg “curse” does not apply to singing, and perhaps Sakagami is the fairy tale prince she has been seeking all along. Will Naruse be able to convey the anthem of her heart?",
        Type: "anime movie",
        Episodes: "1",
        Status: "Finished Airing",
        Aired: "Sep 19, 2015",
        Licensors: "Aniplex of America",
        Studios: "A-1 Pictures",
        Source: "Original",
        Genres: "Drama, Romance, School",
        Duration: "1 hr. 59 min.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "Weathring With You",
        Description: "Tokyo is currently experiencing rain showers that seem to disrupt the usual pace of everyone living there to no end. Amidst this seemingly eternal downpour arrives the runaway high school student Hodaka Morishima, who struggles to financially support himself—ending up with a job at a small-time publisher. At the same time, the orphaned Hina Amano also strives to find work to sustain herself and her younger brother. Both fates intertwine when Hodaka attempts to rescue Hina from shady men, deciding to run away together. Subsequently, Hodaka discovers that Hina has a strange yet astounding power: the ability to call out the sun whenever she prays for it. With Tokyo’s unusual weather in mind, Hodaka sees the potential of this ability. He suggests that Hina should become a “sunshine girl”—someone who will clear the sky for people when they need it the most. Things begin looking up for them at first. However, it is common knowledge that power always comes with a hefty price…",
        Type: "anime movie",
        Episodes: "1",
        Status: "Finished Airing",
        Aired: "Jul 19, 2019",
        Licensors: "GKIDS",
        Studios: "CoMix Wave Films",
        Source: "Original",
        Genres: "Slice of Life, Drama, Romance, Fantasy",
        Duration: "1 hr. 54 min.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "Patema Inverted",
        Description: "Patema is a plucky young girl from an underground civilization boasting an incredible network of tunnels. Inspired by a friend that mysteriously went missing, she is often reprimanded due to her constant excursions of these tunnels due to her royal status. After she enters what is known as the “forbidden zone,” she accidentally falls into a giant bottomless pit after being startled by a strange creature.\nFinding herself on the surface, a world literally turned upside down, she begins falling towards the sky only to be saved by Age, a discontented student of the totalitarian nation known as Aiga.The people of Aiga are taught to believe that “Inverts, ” like Patema, are sinners that will be “swallowed by the sky, ” but Age has resisted this propaganda and decides to protect his new friend.A chance meeting between two curious teenagers leads to an exploration of two unique worlds as they begin working together to unveil the secrets of their origins in Sakasama no Patema, a heart- warming film about overcoming differences in order to coexist.",
        Type: "anime movie",
        Episodes: "1",
        Status: "Finished Airing",
        Aired: "Nov 9, 2013",
        Licensors: "NYAV Post, GKIDS",
        Studios: "Studio Rikka, Purple Cow Studio Japan",
        Source: "Original",
        Genres: "Adventure, Sci-Fi",
        Duration: "1 hr. 39 min.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "Children of the Sea",
        Description: "One summer vacation, Ruka meets two boys, “Umi” and “Sora,” whose upbringing contains strange and wonderful secrets. Drawn to their beautiful swimming, almost more like flying, Ruka and the adults who know them are intertwined in a complex mesh… Meanwhile, an unexplained anomaly is occurring all over the world: fish are disappearing. Thus begins a marine adventure of boys and girls to captivate all the senses!",
        Type: "anime movie",
        Episodes:"1",
        Status: "Finished Airing",
        Aired: "Jun 7, 2019",
        Licensors:"None found, add some",
        Studios: "Studio 4°C",
        Source: "Manga",
        Genres: "Drama, Mystery, Seinen, Supernatural",
        Duration: "1 hr. 51 min.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "The Girl Who Leapt Through Time",
        Description: "Makoto Konno is in her last year of high school, but is having a hard time deciding what to do with her future. In between enduring the pressure of her teachers and killing time with her best friends, Makoto’s life suddenly changes when she accidentally discovers that she is capable of literally leaping through time.\nToki wo Kakeru Shoujo follows Makoto as she plays around with her newfound power.However, she soon learns the hard way that every choice has a consequence, and time is a lot more complicated than it may seem.",
        Type: "anime movie",
        Episodes: "1",
        Status: "Finished Airing",
        Aired: "Jul 15, 2006",
        Licensors: "Funimation, Bandai Entertainment, Kadokawa Pictures USA",
        Studios: "madhouse",
        Source: "Novel",
        Genres: "Adventure, Drama, Romance, Sci-Fi",
        Duration: "1 hr. 38 min.",
        Rating: "PG-Children",
    },
    {
        name: "Wolf Children",
        Description: "Hana, a hard-working college student, falls in love with a mysterious man who attends one of her classes though he is not an actual student. As it turns out, he is not truly human either. On a full moon night, he transforms, revealing that he is the last werewolf alive. Despite this, Hana’s love remains strong, and the two ultimately decide to start a family.\nHana gives birth to two healthy children—Ame, born during rainfall, and Yuki, born during snowfall—both possessing the ability to turn into wolves, a trait inherited from their father.All too soon, however, the sudden death of her lover devastates Hana’s life, leaving her to raise a peculiar family completely on her own.The stress of raising her wild- natured children in a densely populated city, all while keeping their identity a secret, culminates in a decision to move to the countryside, where she hopes Ame and Yuki can live a life free from the judgments of society.Wolf Children is the heartwarming story about the challenges of being a single mother in an unforgiving modern world.",
        Type: "anime movie",
        Episodes: "1",
        Status: "Finished Airing",
        Aired: "Jul 21, 2012",
        Licensors: "Funimation",
        Studios: "Studio Chizu",
        Source: "Original",
        Genres: "Fantancy, Slice of Life",
        Duration: "1 hr. 57 min.",
        Rating: "PG-Children",
    },
    {
        name: "5 Centimeters Per Second",
        Description: "What happens when two people love each other but just aren’t meant to be together? Takaki Toono and Akari Shinohara are childhood friends, but circumstances beyond their control tear them apart.\nThey promise to stay in contact, and although the progression of time widens the distance between them, the chain of memories remains ever- present.Byousoku 5 Centimeter is a romantic drama that focuses on the mundane and harsh reality of long - distance relationships.Stuck in the past and unable to make any new memories, Takaki and Akari cling to the hope of seeing each other again.They live their everyday lives half - heartedly, both hurting themselves and the people around them.",
        Type: "anime movie",
        Episodes: "3",
        Status: "Finished Airing",
        Aired: "Mar 3, 2007",
        Licensors: "ADV Films, Bandai Entertainment, Discotek Media, Crunchyroll",
        Studios: "CoMix Wave Films",
        Source: "Original",
        Genres: "Drama, Romance, Slice of Life",
        Duration: "22 min.per ep.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "Fireworks",
        Description: "It’s summer, and Norimichi Shimada and his friends want to know if fireworks look round or flat from the side. They forge a plan to find the answer at Moshimo Festival’s fireworks display. However, Norimichi finds himself conflicted when his classmate, Nazuna Oikawa, plans to run away from home and wants Norimichi to join her. When things go awry in their attempt to escape, a strange orb in Nazuna’s possession gives them another chance at staying together.",
        Type: "anime movie",
        Episodes: "1",
        Status: "Finished Airing",
        Aired: "Aug 18, 2017",
        Licensors: "NYAV Post, GKIDS",
        Studios: "Shaft",
        Source: "Other",
        Genres: "Romance, Sci-Fi",
        Duration: "1 hr. 30 min.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "Perfect Blue ",
        Description: "J-pop idol group CHAM! has spent the last two years entertaining its fans. Sadly, all good things must come to an end, and CHAM! must see one of its members, Mima Kirigoe, leave the group to pursue her acting career. While Mima’s choice is met with a mixed response, she hopes her fans will continue to support her.\nHowever, Mima’s life begins to change drastically after her departure from the group.Wanting to shed her pop- idol image, she takes on a role in a crime drama series, and her career as an actress gradually becomes more demanding and taxing for both Mima and her manager, Rumi Hidaka.To add to Mima’s growing unease, an obsessed fan who is incapable of accepting that Mima has quit being an innocent idol, begins stalking her; a new anonymous website begins to impersonate her life with intricate detail; and CHAM! also appears to be doing better without her.One by one, each disturbing development drives Mima to become increasingly unhinged and unable to distinguish reality from fantasy.",
        Type: "anime movie",
        Episodes: "1",
        Status: "Finished Airing",
        Aired: "Feb 28, 1998",
        Licensors: "GKIDS, Manga Entertainment",
        Studios: "Madhouse",
        Source: "Novel",
        Genres: "Dementia, Drama, Horror, Psychological",
        Duration: "1 hr. 20 min.",
        Rating: "R+ – Mild Nudity",
    },
    {
        name: "Spirited Away",
        Description: "Stubborn, spoiled, and naïve, 10-year-old Chihiro Ogino is less than pleased when she and her parents discover an abandoned amusement park on the way to their new house. Cautiously venturing inside, she realizes that there is more to this place than meets the eye, as strange things begin to happen once dusk falls.\nGhostly apparitions and food that turns her parents into pigs are just the start—Chihiro has unwittingly crossed over into the spirit world.Now trapped, she must summon the courage to live and work amongst spirits, with the help of the enigmatic Haku and the cast of unique characters she meets along the way.Vivid and intriguing, Sen to Chihiro no Kamikakushi tells the story of Chihiro’s journey through an unfamiliar world as she strives to save her parents and return home.",
        Type: "anime movie",
        Episodes: "1",
        Status: "Finished Airing",
        Aired: "Jul 20, 2001",
        Licensors: "Walt Disney Studios, GKIDS",
        Studios: "Studio Ghibli",
        Source: "Original",
        Genres: "Adventure, Supernatural, Drama",
        Duration: "2 hr 5 min.",
        Rating: "PG-Children",
    },
    {
        name: "The Boy and the Beast",
        Description: "Two souls, living very different lives, wander alone and isolated in their respective worlds. For nine-year-old Ren, the last person who treated him with any form of kindness has been killed and he is shunned by what is left of his family. With no parents, no real family, and no place to go, Ren escapes into the confusing streets and alleyways of Shibuya. Through the twists and turns of the alleys, Ren stumbles into the intimidating Kumatetsu, who leads him to the beast realm of Shibuten.\nFor Kumatetsu, the boy represents a chance for him to become a candidate to replace the Lord of the realm once he retires.While nearly unmatched in combat, Kumatetsu’s chilly persona leaves him with no disciples to teach and no way to prove he is worthy of becoming the Lord’s successor.While the two share different goals, they agree to help each other in order to reach them.Kumatetsu searches for recognition; Ren, now known as Kyuuta, searches for the home he never had.As the years pass by, it starts to become apparent that the two are helping each other in more ways than they had originally thought.Perhaps there has always been less of a difference between them, a boy and a beast, than either of the two ever realized.",
        Type: "anime movie",
        Episodes: "1",
        Status: "Finished Airing",
        Aired: "Jul 11, 2015",
        Licensors: "Funimation",
        Studios: "Studio Chizu",
        Source: "original",
        Genres: "Adventure, Supernatural",
        Duration: "1 hr. 59 min.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "A Silent Voice",
        Description: "As a wild youth, elementary school student Shouya Ishida sought to beat boredom in the cruelest ways. When the deaf Shouko Nishimiya transfers into his class, Shouya and the rest of his class thoughtlessly bully her for fun. However, when her mother notifies the school, he is singled out and blamed for everything done to her. With Shouko transferring out of the school, Shouya is left at the mercy of his classmates. He is heartlessly ostracized all throughout elementary and middle school, while teachers turn a blind eye. Now in his third year of high school, Shouya is still plagued by his wrongdoings as a young boy. Sincerely regretting his past actions, he sets out on a journey of redemption: to meet Shouko once more and make amends. Koe no Katachi tells the heartwarming tale of Shouya’s reunion with Shouko and his honest attempts to redeem himself, all while being continually haunted by the shadows of his past.",
        Type: "anime movie",
        Episodes:"1",
        Status: "Finished Airing",
        Aired: "Sep 17, 2016",
        Licensors:"Eleven Arts, NYAV Post",
        Studios: "Kyoto Animation",
        Source: "Manga",
        Genres: "Drama, School, Shounen",
        Duration: "2 hr 10 min.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "A Whisker Away",
        Description: "Miyo Sasaki, nicknamed “Muge” meaning “infinitely mysterious,” has a bright personality and is full of energy at school and at home. She is also in love with her classmate Kento Hinode. Miyo tries repeatedly to get Kento’s attention, but he takes no notice of her. She realizes that the only way to get close to him is to transform into a cat, but at some point, the boundary between herself and the cat becomes ambiguous.",
        Type: "anime movie",
        Episodes: "1",
        Status: "Finished Airing",
        Aired: "Jun 18, 2020",
        Licensors: "None found, add some",
        Studios: "Studio Colorido",
        Source: "Original",
        Genres: "Drama, Magic, Romance",
        Duration: " 1 hr. 44 min.",
        Rating: "None",
    },
    {
        name: "Her Blue Sky",
        Description: "High school student Aoi Aioi lives with her elder sister, Akane, after a tragic accident took their parents away 13 years ago. Because Akane has since been taking care of her single-handedly, Aoi wants to move to Tokyo after her graduation to relieve her sister’s burden and pursue a musical career, inspired by Akane’s ex-boyfriend Shinnosuke “Shinno” Kanamuro. Shinno was part of a band until he left for Tokyo to become a professional guitarist after the sisters’ parents passed away, and he was never to be seen again.\nOne afternoon, while Aoi practices her bass in a guest house, she gets startled by the 18-year - old version of Shinno from 13 years ago! As if by coincidence, the current 31-year - old Shinno also returns to the town, but he has changed drastically.There are now two Shinno’s in existence, but why is the Shinno from the past present? Sora no Aosa wo Shiru Hito yo revolves around these four individuals as they confront their inner feelings toward each other and make decisions that will affect their lives from here on out.",
        Type: "anime movie",
        Episodes: "1",
        Status: "Finished Airing",
        Aired: "Oct 11, 2019",
        Licensors: "None found, add some",
        Studios: "CloverWorks",
        Source: "Original",
        Genres: "Drama",
        Duration: "1 hr. 55 min.",
        Rating: "PG-13 – Teens 13 or older",
    },
    {
        name: "Hello World",
        Description: "The year is 2027, and the city of Kyoto has undergone tremendous technological advancement. Within the city lives Naomi Katagaki, a socially awkward and introverted boy with a love for books, and Ruri Ichigyou, a girl with a cold personality who is often blunt with people, but shares his love for reading. Despite having similar interests, Naomi is afraid to approach Ruri due to her unfriendly nature. One day, as Naomi goes out for a walk, a crimson aurora pierces through the sky for a brief moment before vanishing. Shortly after, he sees a three-legged crow and a mysterious hooded man who reveals himself to be Naomi from 10 years in the future, explaining that he has come to change an imminent tragic event that happens to Ruri shortly after they start dating.\nInitially taking his words with a grain of salt, present- day Naomi follows his future self’s instructions and starts getting closer to Ruri, determined to save her.Hello World focuses on the present Naomi alongside himself from 10 years into the future.With the help of his future self, Naomi begins his preparations to save Ruri.Will he be able to change the future ?",
        Type: "anime movie",
        Episodes: "1",
        Status: "Finished Airing",
        Aired: "Sep 20, 2019",
        Licensors: "None found, add some",
        Studios: "Graphinica",
        Source: "Original",
        Genres: "Sci-Fi, Drama, Romance",
        Duration: "1 hr 37 min.",
        Rating: "None",
    },
]